export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/admin/auth/login',
    LOGOUT: '/api/admin/auth/logout',
    REFRESH: '/api/admin/auth/refresh',
    ME: '/api/admin/auth/me',
    CHANGE_PASSWORD: '/api/admin/auth/change-password',
    REGISTER: '/api/admin/auth/register',
    SETUP: '/api/admin/auth/setup',
    PERMISSIONS: '/api/admin/auth/permissions',
    ADMINS: {
      BASE: '/api/admin/auth/admins',
      BY_ID: (id: string) => `/api/admin/auth/admins/${id}`,
      ACTIVATE: (id: string) => `/api/admin/auth/admins/${id}/activate`,
      DEACTIVATE: (id: string) => `/api/admin/auth/admins/${id}/deactivate`,
    },
  },
  USERS: {
    BASE: '/api/admin/users',
    BY_ID: (id: string) => `/api/admin/users/${id}`,
    BAN: (id: string) => `/api/admin/users/${id}/ban`,
    UNBAN: (id: string) => `/api/admin/users/${id}/unban`,
    SUBSCRIPTIONS: (id: string) => `/api/admin/users/${id}/subscriptions`,
    SUBSCRIPTIONS_ACTIVE: (id: string) => `/api/admin/users/${id}/subscriptions/active`,
    REDEMPTIONS: (id: string) => `/api/admin/users/${id}/redemptions`,
    TRANSACTIONS: (id: string) => `/api/admin/users/${id}/transactions`,
  },
  VENDORS: {
    BASE: '/api/admin/vendors',
    BY_ID: (id: string) => `/api/admin/vendors/${id}`,
    APPROVE: (id: string) => `/api/admin/vendors/${id}/approve`,
    REJECT: (id: string) => `/api/admin/vendors/${id}/reject`,
    SUSPEND: (id: string) => `/api/admin/vendors/${id}/suspend`,
    REACTIVATE: (id: string) => `/api/admin/vendors/${id}/reactivate`,
    COMMISSION_RATE: (id: string) => `/api/admin/vendors/${id}/commission-rate`,
    CARDS: (id: string) => `/api/admin/vendors/${id}/cards`,
    SUBSCRIPTIONS: (id: string) => `/api/admin/vendors/${id}/subscriptions`,
    REDEMPTIONS: (id: string) => `/api/admin/vendors/${id}/redemptions`,
    TRANSACTIONS: (id: string) => `/api/admin/vendors/${id}/transactions`,
    KYC_PENDING: '/api/admin/vendors/kyc/pending',
    KYC_VERIFY: (id: string) => `/api/admin/vendors/${id}/kyc/verify`,
    KYC_REJECT: (id: string) => `/api/admin/vendors/${id}/kyc/reject`,
  },
  STORES: {
    BASE: '/api/admin/stores',
    BY_ID: (id: string) => `/api/admin/stores/${id}`,
    BY_VENDOR: (vendorId: string) => `/api/admin/stores/vendor/${vendorId}`,
    STATUS: (id: string) => `/api/admin/stores/${id}/status`,
    MANAGER: (id: string) => `/api/admin/stores/${id}/manager`,
  },
  BRANCHES: {
    BASE: '/api/admin/branches',
    BY_ID: (id: string) => `/api/admin/branches/${id}`,
    ACTIVE: '/api/admin/branches/active',
    RADIUS: (id: string) => `/api/admin/branches/${id}/radius`,
    ACTIVATE: (id: string) => `/api/admin/branches/${id}/activate`,
    DEACTIVATE: (id: string) => `/api/admin/branches/${id}/deactivate`,
    MANAGERS: (id: string) => `/api/admin/branches/${id}/managers`,
    ASSIGN_MANAGER: (branchId: string, adminId: string) =>
      `/api/admin/branches/${branchId}/assign-manager/${adminId}`,
  },
  MENUS: {
    BY_STORE: (storeId: string) => `/api/admin/menu/store/${storeId}`,
    CATEGORIES: (storeId: string) => `/api/admin/menu/store/${storeId}/categories`,
    ITEMS: (storeId: string) => `/api/admin/menu/store/${storeId}/items`,
  },
  CARDS: {
    BASE: '/api/admin/cards',
    BY_ID: (id: string) => `/api/admin/cards/${id}`,
    BY_VENDOR: (vendorId: string) => `/api/admin/cards/vendor/${vendorId}`,
    SUBSCRIPTIONS_BY_STORE: (storeId: string) => `/api/admin/cards/subscriptions/store/${storeId}`,
    SUBSCRIPTION_BY_ID: (id: string) => `/api/admin/cards/subscriptions/${id}`,
  },
  COUPONS: {
    BASE: '/api/admin/coupons',
    BY_ID: (id: string) => `/api/admin/coupons/${id}`,
    ACTIVE: '/api/admin/coupons/active',
    PENDING: '/api/admin/coupons/pending',
    STATS: '/api/admin/coupons/stats',
    ACTIVATE: (id: string) => `/api/admin/coupons/${id}/activate`,
    DEACTIVATE: (id: string) => `/api/admin/coupons/${id}/deactivate`,
    APPROVE: (id: string) => `/api/admin/coupons/${id}/approve`,
    REJECT: (id: string) => `/api/admin/coupons/${id}/reject`,
    BY_CODE: (code: string) => `/api/admin/coupons/code/${code}`,
  },
  PAYMENTS: {
    BASE: '/api/admin/payments',
    BY_ID: (id: string) => `/api/admin/payments/${id}`,
    STATS: '/api/admin/payments/stats',
    BY_USER: (id: string) => `/api/admin/payments/user/${id}`,
    BY_VENDOR: (id: string) => `/api/admin/payments/vendor/${id}`,
    BY_STATUS: (status: string) => `/api/admin/payments/status/${status}`,
    REFUND: (id: string) => `/api/admin/payments/${id}/refund`,
  },
  WITHDRAWALS: {
    BASE: '/api/admin/withdrawals',
    BY_ID: (id: string) => `/api/admin/withdrawals/${id}`,
    STATS: '/api/admin/withdrawals/stats',
    BY_VENDOR: (id: string) => `/api/admin/withdrawals/vendor/${id}`,
    APPROVE: (id: string) => `/api/admin/withdrawals/${id}/approve`,
    REJECT: (id: string) => `/api/admin/withdrawals/${id}/reject`,
  },
  BANNERS: {
    BASE: '/api/admin/banners',
    BY_ID: (id: string) => `/api/admin/banners/${id}`,
    ACTIVE: '/api/admin/banners/active',
    TODAY: '/api/admin/banners/today',
    STATS: '/api/admin/banners/stats',
    ACTIVATE: (id: string) => `/api/admin/banners/${id}/activate`,
    DEACTIVATE: (id: string) => `/api/admin/banners/${id}/deactivate`,
    // PROVISIONAL — no upload endpoint exists yet for this feature (confirmed:
    // the only working file-upload contract anywhere in the codebase is the
    // vendor app's unrelated POST /api/vendor/stores/my/banner). This path +
    // the { imageUrl } response shape are a guess modeled on that endpoint's
    // multipart/form-data convention (field name "file"). Confirm with
    // backend and update once the real contract exists.
    UPLOAD: '/api/admin/banners/upload',
  },
  NOTIFICATIONS: {
    BASE: '/api/admin/notifications',
    STATS: '/api/admin/notifications/stats',
    SEND: '/api/admin/notifications/send',
    SEND_BULK: '/api/admin/notifications/send/bulk',
    BY_ID: (id: number | string) => `/api/admin/notifications/${id}`,
    BY_USER: (id: string) => `/api/admin/notifications/user/${id}`,
    BY_VENDOR: (id: string) => `/api/admin/notifications/vendor/${id}`,
    // PENDING BACKEND — no push/in-app/template controllers exist in notification-service yet.
    // Paths below describe the anticipated contract (see notification.types.ts).
    PUSH: {
      DEVICES: '/api/admin/notifications/push/devices',
      DEVICE_STATS: '/api/admin/notifications/push/devices/stats',
      DEVICE_BY_ID: (id: number | string) => `/api/admin/notifications/push/devices/${id}`,
      STATS: '/api/admin/notifications/push/stats',
      SEND: '/api/admin/notifications/push/send',
      SEND_BULK: '/api/admin/notifications/push/send/bulk',
    },
    IN_APP: {
      BASE: '/api/admin/notifications/inapp',
      STATS: '/api/admin/notifications/inapp/stats',
      BY_ID: (id: number | string) => `/api/admin/notifications/inapp/${id}`,
      SEND: '/api/admin/notifications/inapp/send',
      SEND_BULK: '/api/admin/notifications/inapp/send/bulk',
    },
    TEMPLATES: {
      BASE: '/api/admin/notifications/templates',
      BY_ID: (id: number | string) => `/api/admin/notifications/templates/${id}`,
      TOGGLE: (id: number | string) => `/api/admin/notifications/templates/${id}/toggle`,
    },
  },
  REPORTS: {
    PAYMENTS_CSV: '/api/admin/reports/payments.csv',
    COMMISSIONS_CSV: '/api/admin/reports/commissions.csv',
    WITHDRAWALS_CSV: '/api/admin/reports/withdrawals.csv',
  },
  ANALYTICS: {
    OVERVIEW: '/api/admin/analytics/overview',
    REVENUE: '/api/admin/analytics/revenue',
    VENDOR_PERFORMANCE: '/api/admin/analytics/vendor-performance',
    COMMISSIONS: '/api/admin/analytics/commissions',
    ORDERS: '/api/admin/analytics/orders',
    PAYMENTS: '/api/admin/analytics/payments',
  },
  SETTINGS: {
    BASE: '/api/admin/settings',
    BY_KEY: (key: string) => `/api/admin/settings/${key}`,
  },
  AUDIT_LOGS: {
    BASE: '/api/admin/audit-logs',
    BY_ID: (id: string) => `/api/admin/audit-logs/${id}`,
    BY_ACTOR: (actorId: string) => `/api/admin/audit-logs/actor/${actorId}`,
    BY_ENTITY: (type: string, id: string) => `/api/admin/audit-logs/entity/${type}/${id}`,
  },
  API_KEYS: {
    BASE: '/api/admin/api-keys',
    BY_ID: (id: string) => `/api/admin/api-keys/${id}`,
    STATS: '/api/admin/api-keys/stats',
    REVOKE: (id: string) => `/api/admin/api-keys/${id}/revoke`,
    ACTIVATE: (id: string) => `/api/admin/api-keys/${id}/activate`,
  },
  PAYMENT_GATEWAY: {
    BY_PROVIDER: (provider: string) => `/api/admin/payment-gateway/${provider}`,
  },
  COMMISSION: {
    BASE: '/api/admin/commissions',
    BY_VENDOR: (id: string) => `/api/admin/commissions/vendor/${id}`,
    SETTLE: (id: string) => `/api/admin/commissions/${id}/settle`,
    SETTLE_ALL: (id: string) => `/api/admin/commissions/vendor/${id}/settle-all`,
    RATE_GLOBAL: '/api/admin/commissions/rate/global',
    RATE_BY_VENDOR: (id: string) => `/api/admin/commissions/rate/vendor/${id}`,
    RATE_HISTORY_GLOBAL: '/api/admin/commissions/rate/history',
    RATE_HISTORY_VENDOR: (id: string) => `/api/admin/commissions/rate/history/vendor/${id}`,
  },
  REDEMPTIONS: {
    ALL: '/api/admin/redemptions/all',
    STATS: '/api/admin/redemptions/stats',
    BY_ID: (id: string) => `/api/admin/redemptions/${id}`,
    BY_STORE: (storeId: string) => `/api/admin/redemptions/store/${storeId}`,
  },
  SEARCH: {
    GLOBAL: '/api/admin/search',
  },
  DASHBOARD: {
    BASE: '/api/admin/dashboard',
  },
} as const
